events {}

http {
    server {
        listen 80;

        # Статика и медиа из общих volumes
        location /static/ {
            alias /static/;
            expires 7d;
        }

        location /media/ {
            alias /media/;
            expires 7d;
        }

        # Проксируем всё остальное на Django
        location / {
            proxy_pass http://django-app:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
